### ISSUE TITLE
Crash upon beating any boss

### ISSUE THREAD

**Issue by ghost** [Zamiell/jud6s#7] opened 2017-02-01 15:43 UTC
I am running the latest Isaac version and latest version of jud6s. This is the only mod I have enabled, the crash has occurred against different bosses.

My platform details:
Debian GNU/Linux Sid (Unstable) [x86_64]
GNOME on X11
Intel graphics

The following is visible in my log file:
`[ASSERT] - Animation::AdvancePosition cannot go backward (new: -1, cur: 166826192)`

**Comment by Zamiell** [comment] 2017-02-01 18:28
Hello. Are you a speedrunner? You might want to be communicating with me through the Discord.

You are the first person to ever report a crash from the Jud6s mod. Thus, I highly suspect that there is some animation-related bug in the Linux version of Isaac. If this is true, it would mean that its not an issue with the mod, its an issue with the base game, and there is nothing that I can do.

After doing some research, if you can find out exactly which bosses cause the error, then you can forward along the information to Nicalis. With that said, I would imagine that fixing bugs in the Linux version is probably at the very bottom of their priority list, especially with them heavily working on the Nintendo Switch AND having a ton of bugs still waiting to be fixed in the Windows version, so the prospects for Linux look grim.

Consider dual booting into Windows to play Isaac and see if you can reproduce the problem there. (Or, even OS X "Hackintosh", if you don't like Windows.)

**Closed as completed** 2017-02-01 20:19 UTC

**Comment by Zamiell** [comment] 2017-02-02 00:07
To put it less verbosely, Jud6s is not currently supported on Linux.

**Comment by Zamiell** [comment] 2017-03-13 18:19
@ywum7fhv0skqh07h Is the issue fixed now in the latest version of Racing+? I've had reports of other Linux users saying it is working now.

**Comment by ghost** [comment] 2017-03-15 10:17
@Zamiell Yes, the mod works flawlessly as far as I am concerned.

**Comment by Zamiell** [comment] 2017-03-15 15:24
Great. It looks like Nicalis came through and patched the problem on Linux I think.
